### PR TITLE
Resolve metric & metadata broadcast race condition

### LINKED ISSUE #32: [BUG] Metric & Metadata senders are not empty by the time finish() is called
**Describe the bug**
Metric & Metadata senders aren't empty by the time `finish()` is called in `elo/lib.rs`. If there were chat performances still in the pipeline, then it will not end up in the final leaderboard.

**To Reproduce**
1. Clone `origin/bug-repro-adventures`
2. Run `BACKFILL=1 cargo run -r`
3. Observe that `Metric sender is not empty! Yielding now.` log is sent.

This is blocking Neuro Adventures from saving properly, and can sometimes be fixed by adding `println()` statements in the right place.

**Expected behavior**
`Metric sender is not empty! Yielding now.` should not be sent in repeat.

**Additional context**
This bug may not be reproducible depending on the platform. It's definitely an async-related issue.

### PR DESCRIPTION
**Pull request by Gaijutsu**
# Changes

This PR has two main units of change, aiming to close #32 (read for background): 
- Splitting MessageProcessor into `Setup` and `Running` variants to ensure no tasks are spawned in new()
- Wrap Metrics and Metadata with a decorator containing a cloned sender and resubscribed receiver in MetricProcessor.new(), and MetadataProcessor.new() respectively. This provides a guarantee that all receivers are subscribed as soon as the constructor returns.

`MetricProcessorSetup` creates the Metric and Metadata processors / channels. Calling `.start()` will consume the `MetricProcessorSetup`, starting processor threads and producing a `MetricProcessorRunning`. `MetricProcessorRunning` is a drop in replacement for the original `MetricProcessor`.

Metric and Metadata now have a `WithReceiver` decorator, which contains a subscribed receiver and sender. These decorators are constructed sync in the Metric and Metadata constructors, ensuring that all receivers are subscribed before the processing continues.

## Checklist

- [x] My code compiles
- [x] I have committed all the files needed to build the project (check if your file is found in `.gitignore`)
- [x] If I'm introducing a new step in the build process, I have documented / automated it
- [x] I have tested my changes (minimally with one Twitch VOD)

### CODE REVIEW

**Comment by jameshi16** [comment]
Based on what GitHub's saying, you might have to rebase the branch.

Also, if possible, can we combine `self.metadata_processor`, `self.metric_processor` and `performances` into one `JoinSet<()>` to be dropped in `finish`?

**Comment by Gaijutsu** [comment]
Thanks for the heads up! 

Moving to `JoinSet<()>` required a few extra changes:
- I had a to bump the Tokio version from `1.38.0` to `1.40.0` to use `.join_all()`. 
- The performance processor uses a Tokio oneshot channel to return the HashMap of performances instead of returning them directly

File: rust/elo/src/lib.rs [hunk 1]
```diff
@@ -16,42 +18,79 @@ pub mod leaderboards;
...
-        Self {
-            metric_processor_task: tokio::task::spawn(async move { metric_processor.run().await }),
-            metric_sender,
-            metadata_processor_task: tokio::task::spawn(
-                async move { metadata_processor.run().await },
-            ),
-            metadata_sender,
-            performances_task: tokio::task::spawn(performances),
-            sequence_number: AtomicU32::new(0),
+        debug!("Starting message processors");
```
Comment (jameshi16) [inline rust/elo/src/lib.rs:65]: really mad debug line

File: rust/elo/src/lib.rs [hunk 2]
```diff
@@ -16,42 +18,79 @@ pub mod leaderboards;
...
+            metadata_sender: self.metadata_sender,
+            performance_receiver,
+            sequence_number: AtomicU32::new(0)
         }
     }
+}
+
+/// A running message processor that can process messages
+/// 
+/// This struct should not be constructed on its own, it is created by calling `start` on a `MessageProcessorSetup`
```
Comment (jameshi16) [inline rust/elo/src/lib.rs:84]: i think this line might not be necessary, since it would be impossible to construct `MessageProcessorRunning` outside this file (I think)

**Review by jameshi16 — APPROVED** [review]
lgtm, just some nps
